"""
List of programming languages and common coding terms for the 'code' domain.
"""

PROGRAMMING_LANGUAGES = [
    "Python", "JavaScript", "Java", "C", "C++", "C#", "Ruby", "PHP", "Go", "Rust",
    "Swift", "Kotlin", "TypeScript", "Dart", "Scala", "R", "MATLAB", "Perl", "Lua",
    "Haskell", "Erlang", "Elixir", "Clojure", "F#", "Objective-C", "Assembly",
    "SQL", "PL/SQL", "T-SQL", "Visual Basic", "VBA", "Bash", "PowerShell", "Groovy",
    "Julia", "Fortran", "COBOL", "Lisp", "Scheme", "Prolog", "Ada", "Pascal",
    "Delphi", "Smalltalk", "OCaml", "Crystal", "Nim", "Zig", "V", "Solidity",
    "HTML", "CSS", "Sass", "Less", "XML", "JSON", "YAML", "TOML", "Markdown",
    "LaTeX", "GraphQL", "Regex", "Cython", "Numpy", "Pandas", "TensorFlow",
    "PyTorch", "Django", "Flask", "FastAPI", "Spring", "Rails", "Laravel",
    "React", "Vue", "Angular", "Node.js", "Express", "Next.js", "Nuxt.js",
    "Svelte", "jQuery", "Bootstrap", "Tailwind", "SQLite", "MySQL", "PostgreSQL",
    "MongoDB", "Redis", "GraphQL", "gRPC", "Docker", "Kubernetes", "AWS",
    "Azure", "GCP", "Terraform", "Ansible", "Jenkins", "Git", "GitHub",
    "GitLab", "Bitbucket", "SVN", "Mercurial", "Nginx", "Apache", "Linux",
    "Unix", "Windows", "macOS", "Android", "iOS", "Flutter", "React Native",
    "Electron", "Qt", ".NET", "Unity", "Unreal Engine", "Blender", "Godot",
    "OpenGL", "Vulkan", "DirectX", "WebGL", "Three.js", "D3.js", "NumPy",
    "SciPy", "Scikit-learn", "OpenCV", "Keras", "PyTorch Lightning"
]

CODE_TERMS = {
    "API": "Application Programming Interface",
    "JSON": "JavaScript Object Notation",
    "XML": "eXtensible Markup Language",
    "HTML": "HyperText Markup Language",
    "CSS": "Cascading Style Sheets",
    "HTTP": "HyperText Transfer Protocol",
    "HTTPS": "HTTP Secure",
    "FTP": "File Transfer Protocol",
    "SSH": "Secure Shell",
    "DNS": "Domain Name System",
    "TCP/IP": "Transmission Control Protocol / Internet Protocol",
    "UDP": "User Datagram Protocol",
    "IP": "Internet Protocol",
    "URL": "Uniform Resource Locator",
    "URI": "Uniform Resource Identifier",
    "OOP": "Object-Oriented Programming",
    "FP": "Functional Programming",
    "IDE": "Integrated Development Environment",
    "SDK": "Software Development Kit",
    "CLI": "Command Line Interface",
    "GUI": "Graphical User Interface",
    "ORM": "Object-Relational Mapping",
    "MVC": "Model-View-Controller",
    "REST": "Representational State Transfer",
    "SOAP": "Simple Object Access Protocol",
    "SQL": "Structured Query Language",
    "NoSQL": "Not Only SQL",
    "ACID": "Atomicity, Consistency, Isolation, Durability",
    "CRUD": "Create, Read, Update, Delete",
    "JSX": "JavaScript XML",
    "JS": "JavaScript",
    "TS": "TypeScript",
    "CSS": "Cascading Style Sheets",
    "SaaS": "Software as a Service",
    "PaaS": "Platform as a Service",
    "IaaS": "Infrastructure as a Service",
    "LLM": "Large Language Model",
    "AI": "Artificial Intelligence",
    "ML": "Machine Learning",
    "DL": "Deep Learning",
    "NLP": "Natural Language Processing",
    "CV": "Computer Vision",
    "KNN": "K-Nearest Neighbors",
    "SVM": "Support Vector Machine",
    "RNN": "Recurrent Neural Network",
    "CNN": "Convolutional Neural Network",
    "LSTM": "Long Short-Term Memory",
    "GAN": "Generative Adversarial Network",
    "GPU": "Graphics Processing Unit",
    "CPU": "Central Processing Unit",
    "RAM": "Random Access Memory",
    "ROM": "Read-Only Memory",
    "SSD": "Solid State Drive",
    "HDD": "Hard Disk Drive",
    "USB": "Universal Serial Bus",
    "VCS": "Version Control System",
    "CI/CD": "Continuous Integration / Continuous Deployment",
    "TDD": "Test-Driven Development",
    "BDD": "Behavior-Driven Development",
    "DRY": "Don't Repeat Yourself",
    "KISS": "Keep It Simple, Stupid",
    "SOLID": "Single responsibility, Open-closed, Liskov substitution, Interface segregation, Dependency inversion",
    "YAGNI": "You Aren't Gonna Need It",
    "Regex": "Regular Expression",
    "SQLite": "Lightweight disk-based database",
    "MySQL": "Open-source relational database",
    "PostgreSQL": "Advanced open-source relational database",
    "MongoDB": "Document-oriented NoSQL database",
    "Redis": "In-memory data structure store",
    "Docker": "Containerization platform",
    "Kubernetes": "Container orchestration system",
    "Git": "Distributed version control system",
    "GitHub": "Web-based Git repository hosting",
    "Bitbucket": "Git-based source code repository hosting",
    "Jira": "Issue tracking and project management",
    "Confluence": "Team collaboration software",
    "Slack": "Team communication platform",
    "Trello": "Project management tool",
    "Postman": "API testing tool",
    "Swagger": "API documentation tool",
    "npm": "Node Package Manager",
    "pip": "Python Package Installer",
    "yarn": "Package manager for JavaScript",
    "composer": "Dependency manager for PHP",
    "cargo": "Package manager for Rust",
    "brew": "Package manager for macOS",
    "apt": "Package manager for Debian/Ubuntu",
    "yum": "Package manager for RPM-based systems",
    "conda": "Package and environment manager",
    "virtualenv": "Python virtual environment tool",
    "webpack": "Module bundler for JavaScript",
    "Vite": "Frontend build tool",
    "Babel": "JavaScript compiler",
    "ESLint": "JavaScript linter",
    "Prettier": "Code formatter",
    "Jupyter": "Interactive computing environment",
    "PyCharm": "Python IDE",
    "VS Code": "Visual Studio Code editor",
    "IntelliJ": "IDE for JVM languages",
    "Eclipse": "IDE for Java and other languages",
    "Xcode": "IDE for Apple platforms",
    "Android Studio": "IDE for Android development",
    "Arduino": "Electronics platform",
    "Raspberry Pi": "Single-board computer",
    "Linux": "Open-source operating system kernel",
    "Unix": "Multitasking, multiuser operating system",
    "Windows": "Microsoft operating system",
    "macOS": "Apple desktop operating system",
    "Android": "Mobile operating system by Google",
    "iOS": "Mobile operating system by Apple",
    "Flutter": "UI toolkit for building natively compiled applications",
    "React Native": "Framework for building native apps using React",
    "Electron": "Framework for building desktop apps with web technologies",
    "Qt": "Cross-platform application framework",
    "Unity": "Game engine",
    "Unreal Engine": "Game engine",
    "Blender": "3D creation suite",
    "Godot": "Game engine",
    "OpenGL": "Open Graphics Library",
    "Vulkan": "Low-overhead graphics API",
    "DirectX": "Microsoft APIs for multimedia",
    "WebGL": "JavaScript API for 3D graphics",
    "Three.js": "JavaScript 3D library",
    "D3.js": "Data-Driven Documents",
    "NumPy": "Numerical Python library",
    "SciPy": "Scientific computing library",
    "Scikit-learn": "Machine learning library",
    "OpenCV": "Computer vision library",
    "Keras": "Deep learning API",
    "PyTorch Lightning": "Lightweight PyTorch wrapper"
}

def get_language_list():
    return PROGRAMMING_LANGUAGES

def get_code_terms():
    return CODE_TERMS